fixtures:
  forge_modules:
    archive:
      repo: puppet/archive
      ref: 0.5.1
    stdlib:
      repo: puppetlabs/stdlib
      ref: 4.11.0
    java:
      repo: puppetlabs/java
      ref: 1.6.0
    datacat:
      repo: richardc/datacat
      ref: 0.6.2
    apt:
      repo: puppetlabs/apt
      ref: 2.2.2
    yum:
      repo: puppet/yum
      ref: 2.2.0
    zypprepo:
      repo: darin/zypprepo
      ref: 1.0.2
    java_ks: puppetlabs/java_ks
    sysctl:
      repo: thias/sysctl
      ref: 1.0.6
  symlinks:
    elasticsearch_old: "#{source_dir}"
